In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("500hits.csv",encoding = "latin-1")

In [4]:
df.head() #Shows First Five rows

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [5]:
X = df.drop(columns =['PLAYER', 'HOF'])

In [6]:
Y = df["HOF"] #Selecting a single column

In [7]:
X.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329

In [8]:
X.shape # Show Dimesionality (Rows,Columns)

(465, 14)

In [9]:
Y.shape

(465,)

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,random_state = 11, test_size = 0.2)

In [11]:
X_train.shape

(372, 14)

In [12]:
X_test.shape

(93, 14)

In [13]:
Y_train.shape

(372,)

In [14]:
Y_test.shape

(93,)

In [15]:
X_train.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
289,18,2028,7298,873,1993,284,40,325,1163,620,1313,20,38,0.273
288,13,1836,6826,856,1996,392,117,43,402,513,360,247,108,0.292
350,14,1799,6373,876,1854,282,64,49,630,844,627,37,51,0.291
196,17,2158,7911,1057,2276,414,92,94,844,690,784,246,138,0.288
184,19,2390,8570,1386,2369,420,65,244,1084,1197,1099,143,75,0.276

In [16]:
X_train.describe().round()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
count,372.0,372.0,372.0,372.0,372.0,372.0,372.0,372.0,372.0,372.0,372.0,372.0,372.0,372.0
mean,17.0,2047.0,7526.0,1154.0,2178.0,383.0,78.0,203.0,901.0,780.0,850.0,197.0,59.0,0.0
std,3.0,351.0,1302.0,291.0,427.0,97.0,49.0,142.0,484.0,327.0,473.0,186.0,49.0,0.0
min,11.0,1331.0,4981.0,651.0,1660.0,177.0,3.0,9.0,0.0,239.0,0.0,7.0,0.0,0.0
25%,15.0,1798.0,6508.0,936.0,1838.0,312.0,41.0,80.0,645.0,536.0,448.0,64.0,23.0,0.0
50%,17.0,1992.0,7237.0,1099.0,2080.0,367.0,67.0,186.0,978.0,719.0,844.0,141.0,52.0,0.0
75%,19.0,2246.0,8198.0,1305.0,2384.0,436.0,108.0,293.0,1218.0,961.0,1234.0,286.0,84.0,0.0
max,26.0,3308.0,12364.0,2295.0,4189.0,792.0,309.0,755.0,2297.0,2190.0,1936.0,1406.0,335.0,0.0

In [17]:
X_test.describe().round()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
count,93.0,93.0,93.0,93.0,93.0,93.0,93.0,93.0,93.0,93.0,93.0,93.0,93.0,93.0
mean,17.0,2057.0,7453.0,1135.0,2139.0,375.0,80.0,195.0,867.0,797.0,836.0,192.0,54.0,0.0
std,3.0,369.0,1265.0,284.0,415.0,94.0,52.0,152.0,495.0,329.0,552.0,167.0,43.0,0.0
min,11.0,1399.0,5472.0,601.0,1660.0,206.0,14.0,15.0,0.0,266.0,15.0,8.0,0.0,0.0
25%,15.0,1820.0,6622.0,935.0,1818.0,310.0,45.0,78.0,618.0,527.0,359.0,61.0,15.0,0.0
50%,17.0,1997.0,7359.0,1108.0,2054.0,361.0,68.0,151.0,926.0,750.0,745.0,137.0,50.0,0.0
75%,19.0,2282.0,8096.0,1283.0,2256.0,432.0,99.0,291.0,1138.0,937.0,1179.0,271.0,83.0,0.0
max,25.0,2850.0,10876.0,1859.0,3430.0,668.0,252.0,612.0,1922.0,1747.0,2597.0,744.0,173.0,0.0